-- Firepath initial schema.
-- Auth tables are generated by Better Auth (see worker/db/auth-schema.sql);
-- app tables mirror the client-side object shapes.

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null);

create table "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- Transactions ---------------------------------------------------------------

create table "transactions" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "title" text not null,
  "category" text not null,
  "type" text not null check ("type" in ('income', 'expense')),
  "amount" real not null,
  "date" text not null,
  "platform" text,
  "sourceType" text,
  "sourceId" text,
  "investmentType" text,
  "flowDelta" real,
  "isDemo" integer
);

create index "transactions_user_date_idx" on "transactions" ("userId", "date" desc);
create unique index "transactions_source_idx" on "transactions" ("userId", "sourceType", "sourceId") where "sourceType" is not null;

-- Investment holdings --------------------------------------------------------

create table "etfs" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "symbol" text not null,
  "name" text not null,
  "platform" text,
  "units" real not null,
  "averageCost" real not null,
  "currentPrice" real not null,
  "history" text,
  "isDemo" integer
);

create table "crypto" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "symbol" text not null,
  "name" text not null,
  "platform" text,
  "units" real not null,
  "averageCost" real not null,
  "currentPrice" real not null,
  "history" text,
  "isDemo" integer
);

create table "p2p" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "platform" text not null,
  "name" text not null,
  "invested" real not null,
  "currentValue" real not null,
  "annualRate" real,
  "history" text,
  "isDemo" integer
);

create table "bonds" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "name" text not null,
  "issuer" text,
  "platform" text,
  "nominalValue" real,
  "investedValue" real not null,
  "currentValue" real not null,
  "couponRate" real,
  "maturityDate" text,
  "history" text,
  "isDemo" integer
);

create table "savings_accounts" (
  "id" text not null primary key,
  "userId" text not null references "user" ("id") on delete cascade,
  "name" text not null,
  "institution" text,
  "balance" real not null,
  "target" real,
  "annualRate" real,
  "history" text,
  "isDemo" integer
);

create index "etfs_user_idx" on "etfs" ("userId");
create index "crypto_user_idx" on "crypto" ("userId");
create index "p2p_user_idx" on "p2p" ("userId");
create index "bonds_user_idx" on "bonds" ("userId");
create index "savings_user_idx" on "savings_accounts" ("userId");

-- Per-user settings and profile (one row per user) ---------------------------

create table "user_settings" (
  "userId" text not null primary key references "user" ("id") on delete cascade,
  "name" text,
  "avatar" text,
  "createdAt" text,
  "language" text,
  "fireGoal" real,
  "fireMeterVisible" integer,
  "investmentVisibility" text,
  "platforms" text,
  "customCategories" text
);
